# run repoman

sudo: false
language: python
cache: pip

services:
  - docker

python:
  - 3.6

notifications:
  email: false

git:
  depth: 1

branches:
  except:
    - travis-artifacts

matrix:
  fast_finish: true

before_cache:
    - rm -v -f ${HOME}/.cache/pip/log/debug.log

install:
  - pip install jinja2 lxml pyyaml
  - docker pull asciidoctor/docker-asciidoctor

before_script:
  - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr /var /var/cache
  - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
  - echo "portage::250:portage,travis" >> /etc/group

  - mkdir -p "${HOME}/portage" /etc/portage /var/cache/distfiles /var/db/repos/gentoo
  - sudo mkdir /usr/lib/portage
  - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd

  - ln -s /usr/portage/profiles/default/linux/amd64/17.0 /etc/portage/make.profile

script:
  - .travis/script.sh
  - python3 .travis/genlist.py
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf *.adoc

after_script:
  - git config user.name "Deployment Bot (from Travis CI)"
  - git config user.email "deploy@travis-ci.org"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git branch -D travis-artifacts
  - git checkout --orphan travis-artifacts
  - git add .
  - git commit -m "Deploy build ${TRAVIS_BUILD_NUMBER}"
  - git push --force --set-upstream origin travis-artifacts

